#!/bin/bash
#
if [ $# -ne 1 ]; then
	echo "Kasutsjuhend: $0 failinimi"
else
	fail=$1
	if [ -f $fail -a -r $fail ]; then
		echo "fail on korras"
		for rida in $(cat $fail)
		do
			kasutaja=$(echo "$rida" | cut -f1 -d:)
			sh lisa_kasutaja $kasutaja
			echo "$rida" | chpasswd
		done
	else
		echo "probleem failiga $fail"
	fi
fi
